### ISSUE TITLE
Are you interested in me setting up travis-ci?

### ISSUE THREAD

**Issue by chrisosaurus** [wolfgangj/bone-lisp#13]
If you're interested I would be more than happy to try setup automated travis-ci build and testing, that way every PR would be tested automatically before it is merged across all the platforms and compilers we care about.

**Comment by wolfgangj** [comment]
Yes, it would certainly be useful, please go ahead.

**Comment by chrisosaurus** [comment]
I am happy to write the travis configs and do all the work, I do need some support from a current admin of this project.

Someone with admin rights needs to authorise travis-ci so that it can setup the hooks to be notified on every event.

Please visit https://travis-ci.org/wolfgangj/bone-lisp
sign in with github
authorise it for your account
then on https://travis-ci.org/wolfgangj/bone-lisp
there should be a gray box next to bone-lisp, clicking it will turn it green
once green we are good to go and I can do the rest via PRs :)

**Comment by wolfgangj** [comment]
Done.
