### ISSUE TITLE
Version 0.5.0

### ISSUE THREAD

**Issue by wolfgangj** [wolfgangj/bone-lisp#16]
Current plan for 0.5.0:
- I am working on a command line option parser in `std/prog-arg`, which I would like to include.
- I would like to add POSIX bindings for `execve` and `strerror`.
- As a minor point, I want to add a few testcases for things in the prelude.

**Comment by chrisosaurus** [comment]
Thank you for putting this up, very helpful to now the current priorities.

**Comment by wolfgangj** [comment]
POSIX bindings are done now. Getting close to next release.
